version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - revive
    - gosec
    - gocritic
    - misspell
    - unparam
  exclusions:
    presets:
      - comments
      - std-error-handling

formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      module-path: github.com/giovalgas/envault
